#+startup:fold -*- buffer-read-only: t -*- 
#
# this is a set of short notes complementing the MIDAS documentation at 

            https://daq00.triumf.ca/MidasWiki/index.php
# ------------------------------------------------------------------------------
** setup :                                                                   
- install midas, define environment variables:
  MIDAS_EXPT_NAME, MIDAS_EXPTAB, define MIDASSYS
#+begin_quote example                                                        
mu2etrk@mu2edaq22:~/test_stand/pasha_031>env | grep MIDAS
MIDAS_EXPTAB=/home/mu2etrk/test_stand/pasha_031/config/midas/test_025.exptab
MIDASSYS=/home/mu2etrk/test_stand/pasha_031/spack/var/spack/environments/murat/.spack-env/view
MIDAS_EXPT_NAME=test_025
#+end_quote 
** elog                                                                      
*** built-in elog                                                            
- The built-in elog data are stored in the directory defined by the "/Logger/Elog dir" ODB key. 
- If that is not defined, the built-in elog directory is defined by the "/Logger/Data dir" ODB key.
** Equipment update thresholds - slow controls                               
- in the "Equipment/XXX/Settings/Update Threshold" the defaults are set to 0.1
- for low voltages, the update thresholds may need to be customized

- can't build list of equipment dynamically as register_equipment is called before frontend_init
** sequencer                                                                 
- location of the sequencer scripts: key="/Sequencer/State/Path"
- this path is added to $experiment/userfiles , where $experiment is the location
::  of the experiment specified in the $MIDAS_EXPTAB file (see file:config/midas/test_025.exptab)
- proposed for Mu2e: $experiment/online/sequencer
- scripts should be copied there from [[file:../sequencer][frontends/sequencer]] directory, which is 
  a revision-controled area
** history                                                                   
- location of the files:                                                     
- key="/Logger/History dir"
** hotlinks : https://daq00.triumf.ca/elog-midas/Midas/546
** custom pages, javascript                                                  
*** show a value in hex: https://daq00.triumf.ca/elog-midas/Midas/568        
> I have one more question. I use <odb src="odb field" edit=1> to display an 
> editable ODB value, but how can I show this value in hexadecimal?

Again with JavaScript:

  var v = ODBGet('/some/path&format=%X');
** remote frontends                                                          
- start mserver: (by default listens to port 1175) ODB:"/Experiment/Midas server port"
#+begin_src
mserver -D
#+end_src
- set /Experiment/Security/"Enable non-localhost RPC" to "Yes"
- add mhttpd host and remote frontend host to /Experiment/Security/"RPC hosts"/"Allowed hosts"
  mu2edaq09-ctrl.fnal.gov
  mu2edaq22-ctrl.fnal.gov
- start: need to specify the name of the host on which MHTTPD and MSERVER are running
#+begin_src
mu2etrk@mu2edaq22:~/test_stand/pasha_028>cfo_em_frontend -h mu2edaq09-ctrl 
#+end_src

* ------------------------------------------------------------------------------
* back to file:frontends.org
* ------------------------------------------------------------------------------
