#+startup:fold -*- buffer-read-only:t -*- 
# ------------------------------------------------------------------------------
# info on what is TRACE and how to use it
# ------------------------------------------------------------------------------
TRACE is a smart implementation of messaging very useful for debugging 
online applications with multiple processes communicating with each other.

TRACE is intrusive - using it requires instrumenting the application 
with TRACE statements and recompiling the application. 

However, the behaviour of the included TRACE statements can be controled 
from the command line without recompilation.

- user guide        : https://github.com/art-daq/trace/wiki/TRACE-Users-Guide
- TLVL_INFO and such: https://github.com/art-daq/trace/blob/develop/include/TRACE/tracemf2.h#L39-L43
- to be able to set TRACE levels, define TRACE_FILE, for example
#+begin_src
  export TRACE_FILE=/tmp/trace.$USER
#+end_src
- make TRACE_FILE unique for the project


#------------------------------------------------------------------------------
TLOG(TLVL_DEBUG) << "TrackerVST_generator CONSTRUCTOR";

 export TRACE_FILE=/tmp/trace_buffer_pasha.txt

- tshow : see messages that are sent to memory.
- tonM  : turn on additional messages to memory,
- tonS  : send those messages to the log files

 set format of TRACE printouts: TRACE_PRINT="%m-%d %H:%M:%S.%%06d %T %*n %*L %F: %M"

-- TRACE masks: S(slow) M(memory) T(trigger)                                 
- S (slow)   : controls printout directed to stdout, can be redirected to a file
- M (memory) : controls fast printout directed to the shared memory buffer
- T (trigger): controls triggering printout ???
* TRACE_CNTL (traceCntl) - TRACE COMMANDS                                    
- commands :
** cntl
** getcpu
** init
** info : get information about the TRACE settings                          
#+begin_src
mu2etrk@mu2e-trk-06:~/daquser_002>trace_cntl info
trace.h rev       = $Revision: 1710 $$Date: 2025-03-31 11:54:02 -0500 (Mon, 31 Mar 2025) $
revision          = $Revision: 1710 $$Date: 2025-03-31 11:54:02 -0500 (Mon, 31 Mar 2025) $
create time       = Mon Jan 26 17:31:29 CST 2026
trace_initialized = 1
fast/mem __func__ = 0           1=force on, 0=TRACE_PRINT, -1=force off
mode              = 0x3         Slow:ON,  Mem:ON
writeIdxCount     = 0x00006dae  entries used: 28078
full              = 0
nameLock          = 0
largestMultiple   = 0xfff8dea0
largestZeroOffset = 0x00072160
trigIdxCnt        = 0x00000000
triggered         = 0
trigActivePost    = 0
limit_cnt_limit   = 0
limit_span_on_ms  = 50
limit_span_off_ms = 50
traceLevel        = 0x00000000000001ff 0x00000000000000ff 0x0000000000000000
num_entries       = 500000
max_msg_sz        = 192         includes system enforced terminator
max_params        = 10
entry_size        = 320
namLvlTbl_ents    = 1022
namLvlTbl_name_sz = 63          not including null terminator
longest_name      = 33
wrIdxCnt offset   = 0x10000     traceControl_rw start
lvls offset       = 0xc0
nams offset       = 0x6090
buffer_offset     = 0x16040
memlen            = 0x98c0000
default TRACE_TIME_FMT="%m-%d %H:%M:%S.%%06d"
default TRACE_SHOW="%H%x%N %T %P %i %C %e %.3L %m" others: a:nargs b:fileName B:paramBytes D:inDent e:nam:ln# n:nam f:convertedMsgfmt_only I:trcId l:lvlNum O/o:color R:retry S:severity s:slot t:tsc u:line x:filtNl X:examineArgData
default TRACE_PRINT="%T %*e %*L %F: %M" others: C:core e:nam:ln# n:nam [n]f:file F:func I:trcId i:threadID l:lvlNum m:msg-insert N:unpadded_trcName O/o:color P:pid S:severity t:insert u:line
Some SHOW/PRINT specifiers take optional modifiers. E.g. PRINT: %#n.mf#/src#
#+end_src
** limit_ms
** lvlmskn, lvlsetn, lvlclrn
** lvlmsk, lvlset, lvlclr
- lvlclr : clear specified bits;
- lvlset : set specified bits
- lvlmsk : set specified bits as a mask
#+begin_src trace_cntl lvlclr                                               
trace_cntl lvlclr 0xfffff 0xfffff 0xfffff -NDTC_Registers # clear 20 lowest bits in all masks for DTC_Registers  
trace_cntl lvlclr 0x100 0x100 0x100 -N*                   # clear bit 8 everywhere 
trace_cntl lvlset -NDtcInterface_print 0x00000000000001ff 0x00000000000fffff 0x0000000000000000  # set bits - can do from ROOT prompt
#+end_src
** mode
** printfd : define descriptor of the output stream (default=/dev/stdout)
** reset
** 
** tonS, tonM, tonT, tonSg, tonMg, tonTg
#+begin_src
tonS () 
{ 
    trace_cntl lvlset 0 `bitN_to_mask "$@"` 0;
    trace_cntl modeS 1
}
#+end_src
** toffS, toffM, toffT, toffSg, toffMg, toffTg
** trace_cntl tids    : show control masks                                   
#+begin_src 
#mu2etrk@mu2edaq09:~/test_stand/pasha_018>tlvls
mode:                                                    M=1                S=1
 TID                                 NAME              maskM              maskS              maskT
---- ------------------------------------ ------------------ ------------------ ------------------
  24                 ConfigurationManager 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
  69           TopLevelTriggerTable_table 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
  72   dtcInterfaceLib/DTCSoftwareCFO.cpp 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
  82      ARTDAQRoutingManagerTable_table 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 135                      WorkLoopManager 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 139                 MacroMakerSupervisor 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 156                 AllSupervisorInfo.cc 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 159                       ReceiverSocket 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 175                              DTC.cpp 0x0000000000000fff 0x0000000000000000 0x0000000000000000
 191         SupervisorDescriptorInfoBase 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 200         ARTDAQBoardReaderTable_table 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 209                              my_cntl 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 211 options_operation_managedocument.cpp 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 226                          DTC_Packets 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 238                  ARTDAQSupervisor.cc 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 239                    MessageFacility.h 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 240                        CONF:LdStrD_C 0x00000000000001ff 0x0000000000000001 0x0000000000000000
 244                     ARTDAQSupervisor 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 259                        DTC_Registers 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 263                 dispatch_mongodb.cpp 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 268                                TRACE 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 280                       FileDB:RDWRT_C 0x00000000000001ff 0x0000000000000001 0x0000000000000000
 282                              Console 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 289                          _TCPConnect 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 303                              MU2EDEV 0x00000000ffffffff 0x00000000000001ff 0x0000000000000000
 311             configureMessageFacility 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 317                        CONF:CrtCfD_C 0x00000000000001ff 0x0000000000000001 0x0000000000000000
 328                     XDAQContextTable 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 352        MessageFacilityTable_table.cc 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 353       ARTDAQDataLoggerTable_table.cc 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 354                    ConsoleSupervisor 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 357                             Iterator 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 374                            Socket.cc 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 376                   FiniteStateMachine 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 386                               Socket 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 389                 CodeEditorSupervisor 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 403                         UDP_mfPlugin 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 416           options_operation_base.cpp 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 417                    ReceiverSocket.cc 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 420                               CfgGUI 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 433                              rocUtil 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 447          ARTDAQDataLoggerTable_table 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 456                        MetricManager 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 469               JSONDocument_utils.cpp 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 486                      json_writer.cpp 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 501                     VisualSupervisor 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 510                            DTC_Types 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 511                           mu2e_event 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 526              provider_connection.cpp 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 544            detail_managedocument.cpp 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 558     ARTDAQEventBuilderTable_table.cc 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 561                   CoreSupervisorBase 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 567                     JSONDocument.cpp 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 573                         COFS:DpFle_C 0x00000000000001ff 0x0000000000000001 0x0000000000000000
 574                               KERNEL 0x00000000000fffef 0x00000000000001ff 0x0000000000000000
 584                            mu2e_main 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 612           ConfigurationGUISupervisor 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 620                 provider_mongodb.cpp 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 641                                  FSM 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 642                     PRVDR:FileDBIX_C 0x00000000000001ff 0x0000000000000001 0x0000000000000000
 645                    GatewaySupervisor 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 652        ARTDAQEventBuilderTable_table 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 653                      JSNU:DocUtils_C 0x00000000000001ff 0x0000000000000001 0x0000000000000000
 656      ARTDAQBoardReaderTable_table.cc 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 664          ARTDAQDispatcherTable_table 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 678   ARTDAQRoutingManagerTable_table.cc 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 686           CorePropertySupervisorBase 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 688                    AllSupervisorInfo 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 690            FESlowControlsTable_table 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 700           MessageFacilityTable_table 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 706             detail_manageconfigs.cpp 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 728              DTCInterfaceTable_table 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 731               ConfigurationManagerRW 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 772                           trace_cntl 0x00000000ffffffff 0x00000000000001ff 0x0000000000000000
 776                             mu2eUtil 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 783                      ARTDAQTableBase 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 796                      JSNU:Document_C 0x00000000000001ff 0x0000000000000001 0x0000000000000000
 800                            TableBase 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 804       provider_mongodb_readwrite.cpp 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 820           DTCInterfaceTable_table.cc 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 824                             mu2e_mem 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 827                           Visualizer 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 863        TopLevelTriggerTable_table.cc 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 893                CoreSupervisorBase.cc 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 900                      json_reader.cpp 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 909      SupervisorDescriptorInfoBase.cc 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 912        CorePropertySupervisorBase.cc 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 917                    ConfigurationTree 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 942         FESlowControlsTable_table.cc 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 949                       CONF:OpLdStr_C 0x00000000000001ff 0x0000000000000001 0x0000000000000000
 955                             mu2e_pci 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 956               RunControlStateMachine 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 957                   WorkLoopManager.cc 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 961                               trace_ 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 969                           MacroMaker 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 973                              mu2edev 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 979              CodeEditorSupervisor.cc 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
 985                       PRVDR:FileDB_C 0x00000000000001ff 0x0000000000000001 0x0000000000000000
 995                             Fragment 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
1003                             WebUsers 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
1008       ARTDAQDispatcherTable_table.cc 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
1017                        CONF:OpBase_C 0x00000000000001ff 0x0000000000000001 0x0000000000000000
1018                  XDAQContextTable.cc 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
1021                              _TRACE_ 0x0000000000000fff 0x00000000000001ff 0x0000000000000000
+end_src

from Andy:
 
 #+begin_src
tonM -N DTC.cpp 0-1000
to set the debug level for DTC.cpp and then looking at the output with
tshow | less
#+end_src 

According to Andy, DTC.cpp is the source file name. Does this mean that the control 
is at source file level ?
** trace_cntl lvlset  : set mask bits (can run at a ROOT prompt)             
#+begin_src
#+end_src
** trig 
* tshow / tdelta : looking at the TRACE memory log:                          
tshow | tdelta -ct 1 -d 1 | head -n 100
* bitN_to_mask : helper function                                             
`bitN_to_mask 2-4` returns '0x1c'
* TRACE functions in ./bin                                                   
#+begin_src
mu2etrk@mu2e-trk-06:~/daquser_002>ls -al /home/mu2etrk/daquser_002/spack/opt/spack/linux-almalinux9-x86_64_v3/gcc-13.1.0/trace-v3_19_00-afffdjmluvl2qjjt7l5wx5qdclml7seo/bin/
total 1560
drwxr-sr-x  2 mu2etrk mu2e   4096 Nov 25 10:06 .
drwxr-sr-x 12 mu2etrk mu2e   4096 Nov 25 10:06 ..
-rwxr-xr-x  1 mu2etrk mu2e  63592 Nov 25 10:06 basic_c
-rwxr-xr-x  1 mu2etrk mu2e  29603 Nov 25 10:05 big_ex.sh
-rwxr-xr-x  1 mu2etrk mu2e   3961 Nov 25 10:05 bitN_to_mask
-rwxr-xr-x  1 mu2etrk mu2e 219216 Nov 25 10:06 example_main
-rwxr-xr-x  1 mu2etrk mu2e  82984 Nov 25 10:06 ex_traceln
-rwxr-xr-x  1 mu2etrk mu2e 114616 Nov 25 10:06 just
-rwxr-xr-x  1 mu2etrk mu2e  82960 Nov 25 10:06 just_recursive
-rwxr-xr-x  1 mu2etrk mu2e 107552 Nov 25 10:06 just_user
-rwxr-xr-x  1 mu2etrk mu2e  55056 Nov 25 10:06 no_std
-rwxr-xr-x  1 mu2etrk mu2e  26584 Nov 25 10:06 no_trace
-rwxr-xr-x  1 mu2etrk mu2e 104520 Nov 25 10:06 ptr_address_string
-rwxr-xr-x  1 mu2etrk mu2e  91048 Nov 25 10:06 TLOG
-rwxr-xr-x  1 mu2etrk mu2e 112904 Nov 25 10:06 tlog-compare
-rwxr-xr-x  1 mu2etrk mu2e  78536 Nov 25 10:06 TLOG_ENTEX
-rwxr-xr-x  1 mu2etrk mu2e  96792 Nov 25 10:06 TLOG_manipulators
-rwxr-xr-x  1 mu2etrk mu2e   5946 Nov 25 10:05 trace_bash
-rwxr-xr-x  1 mu2etrk mu2e    786 Nov 25 10:05 trace_bash_example.sh
-rwxr-xr-x  1 mu2etrk mu2e   2744 Nov 25 10:05 trace-cmd-merge
-rwxr-xr-x  1 mu2etrk mu2e 128664 Nov 25 10:06 trace_cntl
-rwxr-xr-x  1 mu2etrk mu2e   3441 Nov 25 10:05 trace_color
-rwxr-xr-x  1 mu2etrk mu2e  25845 Nov 25 10:05 trace_delta
-rwxr-xr-x  1 mu2etrk mu2e   1581 Nov 25 10:05 trace_envvars
-rwxr-xr-x  1 mu2etrk mu2e   5377 Nov 25 10:05 trace_feature_test.sh
-rwxr-xr-x  1 mu2etrk mu2e   3118 Nov 25 10:05 trace_functions.sh
-rwxr-xr-x  1 mu2etrk mu2e  83696 Nov 25 10:06 trace_lvl
-rwxr-xr-x  1 mu2etrk mu2e   3743 Nov 25 10:05 trace_maxents
#+end_src
* Ron's hints from different setup files and examples                        
 --  enable kernel trace to memory buffer:
#+test -f /proc/trace/buffer && { export TRACE_FILE=/proc/trace/buffer; tlvls | grep 'KERNEL 0xffffffff00ffffff' >/dev/null || { tonMg 0-63; toffM 24-31 -nKERNEL; }; }


if [ -d ${TRACE_BIN} ]; then 
  echo -e "setup [${LINENO}]  \t     Setting up TRACE defaults..."
  # echo Turning on all memory tracing via: tonMg 0-63 
  
  # Default setup moved from setup_trace to here so it can be disabled
  #${TRACE_BIN}/trace_cntl lvlmskg 0xfff 0x1ff 0  # <memory> <slow> <trigger>, tonSg 0-8 (debug is 8 := TLVL_{FATAL,ALERT,CRIT,ERROR,WARNING,NOTICE,INFO,LOG,DEBUG}) OBSOLETE as of 8/08/2023
  ${TRACE_BIN}/trace_cntl mode 3   # ton*
  
  # Disable some very verbose trace outputs 
  TRACE_NAMLVLSET="\
CONF:LdStrD_C    0x1ff 0 0
FileDB:RDWRT_C   0x1ff 0 0
CONF:CrtCfD_C    0x1ff 0 0
COFS:DpFle_C     0x1ff 0 0
PRVDR:FileDBIX_C 0x1ff 0 0
JSNU:DocUtils_C  0x1ff 0 0
JSNU:Document_C  0x1ff 0 0
CONF:OpLdStr_C   0x1ff 0 0
PRVDR:FileDB_C   0x1ff 0 0
CONF:OpBase_C    0x1ff 0 0
" $TRACE_BIN/trace_cntl namlvlset
fi

** using debug+x semantics int tonM                                          
 tonM -N*:farm_manager.py debug+1-debug+20
* from ROOT command prompt                                                   
#+begin_src
root[0] .! trace_cntl lvlset -NDtcInterface 0 0x4 ; trace_cntl modeS 1; trace_cntl tids
#+end_src
* python interface to TRACE.CNTL                                             
** switching TRACE output in python                                          
#+begin_src
sys.stdout  = open(self.tfm_logfile, 'w')
TRACE.CNTL('printfd',sys.stdout.fileno())
#+end_src
* ------------------------------------------------------------------------------
* back to [[file:frontends.org][frontends]]
* ------------------------------------------------------------------------------
