#!/usr/bin/bash

partition=$1
list_of_processes=`ps -efl | grep partition | grep $partition | grep -v cleanup_partition | awk '{print $4}'`
if [ ."$list_of_processes" != "." ] ; then
    echo killing the followng:
    ps -efl | grep partition | grep $partition | grep -v cleanup_partition
    kill -9 $list_of_processes ;
    echo done
else                                  echo "partition $partition is clean";
fi
    
