#!/usr/bin/bash
#------------------------------------------------------------------------------
# on a remote node, supposedly: ./start_dtc_fe -h mu2edaq09-data.fnal.gov
# however, doesn't start properly by MIDAS - needs tuning
#------------------------------------------------------------------------------
host=$1

cmds="cd ~/test_stand/pasha_023 ; source setup_daq.sh ; source setup_midas.sh test_023 ; dtc_frontend -h mu2edaq09-data.fnal.gov &"

screen -dmS dtc_$host bash -c \"ssh $host $cmds\"
