#!/bin/bash
#------------------------------------------------------------------------------
# the farm manager doesn't need to know about MIDAS..
#
# call signature: 
# 
#   start_farm_manager artdaq_config partition [ debug ]
#
# experiment   : MIDAS experiment
# artdaq_config: name of the ARTDAQ configuration
# partition    : ARTDAQ_PARTITION_NUMBER
#
# assumes :
# - presence of the $PWD/setup_daq.sh 
# - presence of the $PWD/config/$artdaq_config
#
# ?? what is needed from setup_daq.sh ? 
# - setting up TFM_DIR and ARTDAQ_PARTITION_NUMBER
#------------------------------------------------------------------------------
artdaq_config=$1
    partition=$2

debug=0 ; if [ -n $3 ] ; then debug=$3 ; fi
#------------------------------------------------------------------------------
# this defines ARTDAQ_PARTITION_NUMBER
#------------------------------------------------------------------------------
source $MU2E_DAQ_DIR/setup_daq.sh $partition

config_dir=$PWD/config/$artdaq_config

if [[ $debug -ne 0 ]] ; then echo "[$0:$LINENO]" config_dir=$config_dir ; fi
#------------------------------------------------------------------------------
# this sets ARTDAQ_PARTITION_NUMBER and TFM_CONFIG_DIR
#------------------------------------------------------------------------------
source $TFM_DIR/bin/tfm_configure $artdaq_config $partition

ts=`date +"%Y%m%d_%H%M%S"`
logfile=/scratch/mu2e/mu2etrk_pasha_023/$artdaq_config/logs/tfm/${ts}-tfm.log

cmd="$TFM_DIR/rc/control/farm_manager.py --config-dir=$config_dir \>\| $logfile 2\>\&1 \&"

if [[ $debug -ne 0 ]] ; then echo "[$0:$LINENO]" $cmd ; fi

$TFM_DIR/rc/control/farm_manager.py --config-dir=$config_dir >| $logfile 2>&1 &
tail -f $logfile

# sleep 10
